/**
 * Cache Configuration
 * 
 * Generated by cache integration script
 */

export const cacheConfig = {
  // Multi-layer cache settings
  multiLayer: {
    l1: {
      maxSize: 1000,
      ttl: 300000 // 5 minutes
    },
    l2: {
      enabled: true,
      ttl: 3600000 // 1 hour
    }
  },
  
  // API response caching
  api: {
    defaultTtl: 300000, // 5 minutes
    routes: {
      '/api/users': 600000, // 10 minutes
      '/api/competencies': 1800000, // 30 minutes
      '/api/rotations': 3600000, // 1 hour
      '/api/dashboard': 300000 // 5 minutes
    }
  },
  
  // Database query caching
  database: {
    defaultTtl: 600000, // 10 minutes
    queries: {
      user: 1800000, // 30 minutes
      competency: 3600000, // 1 hour
      rotation: 7200000, // 2 hours
      evaluation: 300000 // 5 minutes
    }
  },
  
  // Health monitoring
  health: {
    checkInterval: 60000, // 1 minute
    thresholds: {
      critical: {
        hitRate: 0.3,
        errorRate: 0.1,
        avgResponseTime: 1000
      },
      warning: {
        hitRate: 0.5,
        errorRate: 0.05,
        avgResponseTime: 500
      }
    }
  },
  
  // Cache warming
  warming: {
    enabled: true,
    schedule: '0 */6 * * *', // Every 6 hours
    routes: [
      '/api/users',
      '/api/competencies',
      '/api/rotations'
    ]
  }
}

export default cacheConfig
